# Generated by Django 3.1.4 on 2021-05-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210110_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='discordId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='discordUrl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='fbUrl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='instaUrl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
